services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - service_network

  service-registry:
    build:
      context: ./server/service-registry
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    depends_on:
      - redis
    networks:
      - service_network

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=blogger
      - POSTGRES_PASSWORD=blogger_password
      - POSTGRES_DB=blogger_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - service_network

  auth-service:
    build:
      context: ./server/auth
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - DATABASE_URL=postgres://blogger:blogger_password@postgres:5432/blogger_auth?sslmode=disable
      - JWT_SECRET_KEY=your_jwt_secret_key_here
      - REGISTRY_URL=http://service-registry:8080
    depends_on:
      - postgres
      - service-registry
    networks:
      - service_network

networks:
  service_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data: 