version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - service_network

  service-registry:
    build:
      context: ./server/service-registry
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
    depends_on:
      - redis
    networks:
      - service_network

networks:
  service_network:
    driver: bridge

volumes:
  redis_data: 